require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'

Layout/LineLength:
  Max: 180

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/ExampleLength:
  Max: 11

Rails/InverseOf:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/ContentTag:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Rails/FilePath:
  Enabled: false
